// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dinkur} from '../models';

export function ConnectDinkur(arg1:string):Promise<void>;

export function GetActiveEntry():Promise<dinkur.Entry>;
