// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDinkur() {
  return window['go']['app']['App']['ConnectDinkur']();
}

export function DisconnectDinkur() {
  return window['go']['app']['App']['DisconnectDinkur']();
}

export function GetActiveEntry() {
  return window['go']['app']['App']['GetActiveEntry']();
}

export function GetEntriesForDay(arg1) {
  return window['go']['app']['App']['GetEntriesForDay'](arg1);
}
