// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dinkur} from '../models';
import {time} from '../models';

export function ConnectDinkur():Promise<void>;

export function DisconnectDinkur():Promise<void>;

export function GetActiveEntry():Promise<dinkur.Entry>;

export function GetEntriesForDay(arg1:time.Time):Promise<Array<dinkur.Entry>>;
