// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDinkur(arg1) {
  return window['go']['main']['App']['ConnectDinkur'](arg1);
}

export function GetActiveEntry() {
  return window['go']['main']['App']['GetActiveEntry']();
}
